# Generated by Django 6.1.1 on 2026-09-21 18:15

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0002_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='Id de Nierika')),
                ('serial_number', models.CharField(db_index=True, max_length=100, verbose_name='Número de serie')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de emisión')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('max_expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiración máxima')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de revocación')),
                ('scan_kind', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de escaneo')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
            },
        ),
        migrations.CreateModel(
            name='StudentCredential',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de vinculación')),
                ('unlinked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de desvinculación')),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_link', to='credentials.credential', verbose_name='Credencial')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_links', to='school.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Relación estudiante-credencial',
                'verbose_name_plural': 'Relaciones estudiante-credencial',
                'ordering': ('-linked_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('student',), name='studentcredential_one_active_per_student')],
            },
        ),
    ]
