# Generated by Django 6.1.1 on 2026-09-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='scan_kind',
        ),
    ]
