# Generated by Django 6.1.1 on 2026-09-23

from django.db import migrations, models


def delete_credentials_without_max(apps, schema_editor):
    """Elimina filas del espejo sin techo de vigencia.

    El espejo es derivado y re-descargable (sync_nierika_credentials salta
    esas filas), así que borrarlas es seguro y permite el ALTER NOT NULL.
    """
    Credential = apps.get_model('credentials', 'Credential')
    Credential.objects.filter(max_expiration_date__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_remove_credential_scan_kind'),
    ]

    operations = [
        migrations.RunPython(
            delete_credentials_without_max, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='credential',
            name='max_expiration_date',
            field=models.DateTimeField(verbose_name='Expiración máxima'),
        ),
    ]
