[project]
name = "school-attendance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Carlos Sandoval", email = "sycarlos@outlook.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
school-attendance = "school_attendance:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
