# Generated by Django 6.1.1 on 2026-09-21 18:15

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Etiqueta de estación')),
                ('prefix', models.CharField(db_index=True, max_length=16, verbose_name='Prefijo')),
                ('hash', models.CharField(max_length=64, verbose_name='Hash SHA-256')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocada')),
            ],
            options={
                'verbose_name': 'API key de escritorio',
                'verbose_name_plural': 'API keys de escritorio',
                'ordering': ('-created_at',),
            },
        ),
    ]
