"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parents[2]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0i-%3yp(yplp51#me6=rjzmht4%$c^m8y)1e$1u(%o4yvjt5o&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'import_export',
    'django.contrib.admin',
    'accounts',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'django_cotton',
    'django_tailwind_cli',
    'ninja',
    'core_ui',
    'allauth',
    'allauth.account',
    'school',
    'teachers',
    'api',
    'django.forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Authentication: allauth first (account flows), ModelBackend as fallback for admin

AUTHENTICATION_BACKENDS = [
    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = 'accounts.User'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es'

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'teachers:dashboard'
LOGOUT_REDIRECT_URL = 'account_login'

# django-allauth

ACCOUNT_ADAPTER = 'config.adapters.AccountAdapter'

ACCOUNT_LOGIN_METHODS = {'username'}

ACCOUNT_EMAIL_VERIFICATION = 'optional'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Design-system app (cotton components, allauth templates, tailwind assets)

STATICFILES_DIRS = [BASE_DIR / 'src' / 'core_ui' / 'static']

# Tailwind CSS via django-tailwind-cli (uv-only, no node)

TAILWIND_CLI_SRC_CSS = 'src/core_ui/input.css'
TAILWIND_CLI_DIST_CSS = 'core-ui/css/output.css'

# Test discovery for apps living under src/ (tests.py inside each app package)

TEST_RUNNER = 'config.test_runner.SrcLayoutDiscoverRunner'


# Form widget templates: resolve from app template dirs so core_ui can override
# django/forms/widgets/*.html (all default Textareas render via <c-textarea>)

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'


# Django Unfold admin theme
# https://unfoldadmin.com/docs/

UNFOLD = {
    'SITE_TITLE': 'Asistencia Escolar',
    'SITE_HEADER': 'Administración de Asistencia Escolar',
    'SIDEBAR': {
        'navigation': [
            {
                'title': 'Asistencia',
                'items': [
                    {
                        'title': 'Estudiantes',
                        'link': '/admin/school/student/',
                    },
                    {
                        'title': 'Grupos de estudiantes',
                        'link': '/admin/school/studentgroup/',
                    },
                    {
                        'title': 'Sesiones de asistencia',
                        'link': '/admin/school/attendancesession/',
                    },
                    {
                        'title': 'Reportes',
                        'link': '/admin/school/attendancesession/reports/',
                    },
                ],
            },
            {
                'title': 'Académico',
                'items': [
                    {
                        'title': 'Profesores',
                        'link': '/admin/school/teacher/',
                    },
                    {
                        'title': 'Materias',
                        'link': '/admin/school/subject/',
                    },
                    {
                        'title': 'Cursos',
                        'link': '/admin/school/course/',
                    },
                ],
            },
        ],
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
