# Generated by Django 6.1.1 on 2026-09-10 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('paternal_surname', 'maternal_surname', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to='school.student', verbose_name='Estudiantes')),
            ],
            options={
                'verbose_name': 'Grupo de estudiantes',
                'verbose_name_plural': 'Grupos de estudiantes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school.studentgroup', verbose_name='Grupo de estudiantes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school.subject', verbose_name='Materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='school.teacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ('subject__name',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.classroom', verbose_name='Aula')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to='school.teacher', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sesión de asistencia',
                'verbose_name_plural': 'Sesiones de asistencia',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='school.classroom', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clase',
                'ordering': ('classroom', 'weekday', 'start_time'),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='classschedule_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('LATE', 'Tarde'), ('EXCUSED', 'Justificado')], default='PRESENT', max_length=10, verbose_name='Estado')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='school.attendancesession', verbose_name='Sesión')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='school.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ('student__paternal_surname', 'student__maternal_surname', 'student__first_name'),
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_record_session_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'student_group'), name='unique_classroom_teacher_subject_group'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('classroom', 'date'), name='unique_session_classroom_date'),
        ),
    ]
