# Generated by Django 6.1.1 on 2026-09-20 03:29

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paternal_surname', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('maternal_surname', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ('paternal_surname', 'maternal_surname', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SchoolCycle',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cycle_type', models.CharField(choices=[('ANNUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('QUATRIMESTRAL', 'Cuatrimestral')], max_length=15, verbose_name='Tipo de ciclo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Ciclo escolar',
                'verbose_name_plural': 'Ciclos escolares',
                'ordering': ('-start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='schoolcycle_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to='school.student', verbose_name='Estudiantes')),
            ],
            options={
                'verbose_name': 'Grupo de estudiantes',
                'verbose_name_plural': 'Grupos de estudiantes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('classroom', models.CharField(blank=True, default='', max_length=50, verbose_name='Aula')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
                ('school_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.schoolcycle', verbose_name='Ciclo escolar')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.studentgroup', verbose_name='Grupo de estudiantes')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.subject', verbose_name='Materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.teacher', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ('subject__name',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='school.course', verbose_name='Curso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to='school.teacher', verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Sesión de asistencia',
                'verbose_name_plural': 'Sesiones de asistencia',
                'ordering': ('-date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='school.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Horario de clase',
                'verbose_name_plural': 'Horarios de clase',
                'ordering': ('course', 'weekday', 'start_time'),
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='classschedule_start_before_end')],
            },
        ),
        migrations.CreateModel(
            name='NonSchoolDay',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('day_type', models.CharField(choices=[('ASUETO', 'Asueto'), ('VACACIONES', 'Vacaciones'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_school_days', to='school.schoolcycle', verbose_name='Ciclo escolar')),
            ],
            options={
                'verbose_name': 'Día inhábil',
                'verbose_name_plural': 'Días inhábiles',
                'ordering': ('start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='nonschoolday_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('LATE', 'Tarde'), ('EXCUSED', 'Justificado')], default='PRESENT', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='school.attendancesession', verbose_name='Sesión')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='school.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ('student__paternal_surname', 'student__maternal_surname', 'student__first_name'),
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_record_session_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'student_group', 'school_cycle'), name='unique_course_teacher_subject_group_school_cycle'),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('course', 'date'), name='unique_session_course_date'),
        ),
    ]
