# Generated by Django 6.1.1 on 2026-09-20 06:22

from django.db import migrations, models

import school.images


class Migration(migrations.Migration):

    dependencies = [  # noqa: RUF012
        ('school', '0001_initial'),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, storage=school.images.ConvertedPhotoStorage(), upload_to='students/', verbose_name='Fotografía'),
        ),
    ]
