# Generated by Django 6.1.1 on 2026-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_classroom_to_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ('course', 'weekday', 'start_time'), 'verbose_name': 'Horario de clase', 'verbose_name_plural': 'Horarios de clase'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('subject__name',), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_classroom_teacher_subject_group',
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(fields=('course', 'date'), name='unique_session_course_date'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'student_group'), name='unique_course_teacher_subject_group'),
        ),
    ]
