# Generated by Django 6.1.1 on 2026-09-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_read_only_admin_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSchoolDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('day_type', models.CharField(choices=[('ASUETO', 'Asueto'), ('VACACIONES', 'Vacaciones'), ('OTRO', 'Otro')], max_length=10, verbose_name='Tipo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Día inhábil',
                'verbose_name_plural': 'Días inhábiles',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='SchoolCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cycle_type', models.CharField(choices=[('ANNUAL', 'Anual'), ('SEMESTRAL', 'Semestral'), ('QUATRIMESTRAL', 'Cuatrimestral')], max_length=15, verbose_name='Tipo de ciclo')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Ciclo escolar',
                'verbose_name_plural': 'Ciclos escolares',
                'ordering': ('-start_date',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_teacher_subject_group',
        ),
        migrations.AddConstraint(
            model_name='schoolcycle',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='schoolcycle_start_before_end'),
        ),
        migrations.AddField(
            model_name='nonschoolday',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_school_days', to='school.schoolcycle', verbose_name='Ciclo escolar'),
        ),
        migrations.AddField(
            model_name='course',
            name='school_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.schoolcycle', verbose_name='Ciclo escolar'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'student_group', 'school_cycle'), name='unique_course_teacher_subject_group_school_cycle'),
        ),
        migrations.AddConstraint(
            model_name='nonschoolday',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='nonschoolday_end_after_start'),
        ),
    ]
