# Generated by Django 6.1.1 on 2026-09-19 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_nonschoolday_schoolcycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school_cycle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='school.schoolcycle', verbose_name='Ciclo escolar'),
            preserve_default=False,
        ),
    ]
